export const ADD_NEW_ORDER_REQUEST = 'ADD_NEW_ORDER_REQUEST';
export const ADD_NEW_ORDER_SUCCESS = 'ADD_NEW_ORDER_SUCCESS';
export const ADD_NEW_ORDER_FAIL = 'ADD_NEW_ORDER_FAIL';

export const LOAD_ORDERS_HISTORY_REQUEST = 'LOAD_ORDERS_HISTORY_REQUEST';
export const LOAD_ORDERS_HISTORY_SUCCESS = 'LOAD_ORDERS_HISTORY_SUCCESS';
export const LOAD_ORDERS_HISTORY_FAIL = 'LOAD_ORDERS_HISTORY_FAIL';