export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCES = 'USER_LOGIN_SUCCES';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_REGISTER_SUCCES = 'USER_LOGIN_SUCCES';
export const USER_REGISTER_FAIL = 'USER_LOGIN_FAIL';
export const USER_REGISTER_LOGOUT = 'USER_REGISTER_LOGOUT';